import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
let failed=false,requests=[];const time=Math.floor(Date.now()/1000);
await page.route('https://quotes.example/**',route=>{const code=new URL(route.request().url()).searchParams.get('code');requests.push(code);return route.fulfill({status:failed||code==='6758'?502:200,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({code,price:2500.5,currency:'JPY',time,source:'Yahoo Finance'})});});
await page.goto(process.env.APP_URL||'http://127.0.0.1:8080/');
const legacy={version:1,updated:null,assets:[{id:'old',type:'stock',name:'トヨタ',institution:'SBI証券',account:'NISA',shares:100,cost:2000,price:2200}]};
await page.evaluate(d=>localStorage.setItem('my-portfolio-v1',JSON.stringify(d)),legacy);await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('my-portfolio-v1'))),legacy);assert.equal(await page.locator('#total').innerText(),'￥220,000');
await page.locator('#quote-endpoint').fill('https://quotes.example/');await page.locator('#save-endpoint').click();
await page.getByRole('button',{name:'トヨタを編集',exact:true}).click();assert.equal(await page.locator('[name="price"]').count(),0);assert.equal(await page.locator('[name="shares"]').inputValue(),'100');assert.equal(await page.locator('[name="cost"]').inputValue(),'2000');await page.locator('[name="code"]').fill('7203');await page.getByRole('button',{name:'保存する',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#quote-status').textContent.includes('取得 1銘柄'));
assert.equal(await page.locator('#total').innerText(),'￥250,050');assert.equal(await page.locator('#profit').innerText(),'+￥50,050');let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('my-portfolio-v1')));assert.equal(saved.assets[0].shares,100);assert.equal(saved.assets[0].cost,2000);assert.equal(saved.assets[0].quoteTime,time);
failed=true;await page.locator('#refresh-quotes').click();await page.waitForFunction(()=>document.querySelector('#quote-status').textContent.includes('失敗 1銘柄'));assert.equal(await page.locator('#total').innerText(),'￥250,050');assert.equal((await page.locator('.quote-error').count()),1);
await page.getByRole('button',{name:'トヨタを編集',exact:true}).click();await page.locator('[name="code"]').fill('6758');await page.getByRole('button',{name:'保存する',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#quote-status').textContent.includes('失敗 1銘柄'));assert.match(await page.locator('#valuation-warning').innerText(),/未取得/);saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('my-portfolio-v1')));assert.equal(saved.assets[0].price,null);assert.equal(saved.assets[0].shares,100);assert.equal(saved.assets[0].cost,2000);
failed=false;await page.getByRole('button',{name:'トヨタを編集',exact:true}).click();await page.locator('[name="code"]').fill('7203');await page.getByRole('button',{name:'保存する',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#quote-status').textContent.includes('取得 1銘柄'));await page.reload();await page.waitForFunction(()=>document.querySelector('#quote-status').textContent.includes('取得 1銘柄'));assert.equal(await page.locator('#total').innerText(),'￥250,050');
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();assert.equal(await page.locator('#total').innerText(),'￥250,050');assert.deepEqual(errors,[]);
console.log('PASS (mock quotes): legacy data, no manual price input, quote update and totals, failure preservation, code changes, persistence, mobile layout, offline');await browser.close();
