import {TYPES,COLORS,value,cost,summary,institutionSummary,validateAsset,parseBackup} from './model.js';
const $=s=>document.querySelector(s), STORAGE='my-portfolio-v1';
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(n);
const signed=n=>(n>0?'+':'')+yen(n);
let data={version:1,assets:[],updated:null},editing=null,deleting=null;
function notice(message){$('#notice').textContent=message;}
try {const raw=localStorage.getItem(STORAGE);if(raw)data=parseBackup(raw);}catch {notice('保存データを読み込めませんでした。元のデータは上書きせず、バックアップからの復元をお試しください。');$('#add').disabled=true;}
function persist(next){try {localStorage.setItem(STORAGE,JSON.stringify(next));data=next;$('#add').disabled=false;render();return true;}catch {notice('保存できませんでした。ブラウザの空き容量・保存設定を確認してください。');return false;}}
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function render(){const s=summary(data.assets);$('#total').textContent=yen(s.total);$('#profit').textContent=signed(s.profit);$('#profit').className=s.profit<0?'negative':'';$('#rate').textContent=s.rate===null?'—':`${s.rate>0?'+':''}${s.rate.toFixed(1)}%`;$('#updated').textContent=data.updated?`${new Date(data.updated).toLocaleDateString('ja-JP')} 更新`:'まだ登録がありません';$('#category-count').replaceChildren(document.createTextNode(String(Object.values(s.allocation).filter(v=>v>0).length)),node('span','', '種類'));$('#asset-count').textContent=`${data.assets.length}件の資産`;
 let start=0;const stops=[];$('#allocation-list').replaceChildren();for(const [t,label]of Object.entries(TYPES)){const pct=s.total?s.allocation[t]/s.total*100:0;stops.push(`${COLORS[t]} ${start}% ${start+pct}%`);start+=pct;const li=node('li');const left=node('div','legend-name');const dot=node('i');dot.style.background=COLORS[t];left.append(dot,node('span','',label));const right=node('div','legend-value');right.append(node('strong','',yen(s.allocation[t])),node('span','',`${pct.toFixed(1)}%`));li.append(left,right);$('#allocation-list').append(li);}$('#donut').style.background=s.total?`conic-gradient(${stops.join(',')})`:'#e8eeea';
 $('#institutions').replaceChildren();const groups=institutionSummary(data.assets);if(!groups.length)$('#institutions').append(node('p','details','資産を登録すると金融機関ごとの合計が表示されます。'));for(const group of groups){const section=node('div','institution-group');const heading=node('div','institution-heading');heading.append(node('strong','',group.name),node('strong','',yen(group.total)));section.append(heading);for(const account of group.accounts){const row=node('div','account-row');row.append(node('span','',account.name),node('span','',yen(account.total)));section.append(row);}$('#institutions').append(section);}
 $('#assets').replaceChildren();if(!data.assets.length){const empty=node('div','empty');empty.append(node('div','empty-icon','＋'),node('h3','','最初の資産を登録しましょう'),node('p','','現金からでも、保有している株からでも。'));$('#assets').append(empty);}
 for(const a of data.assets){const card=node('article','asset-card');const top=node('div','asset-top');const label=node('div');const badge=node('span','badge',TYPES[a.type]);badge.style.borderColor=COLORS[a.type];label.append(badge,node('h3','',a.name));const actions=node('div','asset-actions');const edit=node('button','','編集');edit.setAttribute('aria-label',`${a.name}を編集`);edit.onclick=()=>openEditor(a);const del=node('button','delete','削除');del.setAttribute('aria-label',`${a.name}を削除`);del.onclick=()=>{deleting=a.id;$('#delete-name').textContent=a.name;$('#delete-dialog').showModal();};actions.append(edit,del);top.append(label,actions);card.append(top,node('p','account-label',a.institution ? `${a.institution} ／ ${a.account}` : '口座未登録 · 編集から設定できます'),node('div','asset-value',yen(value(a))));
 if(a.type==='stock')card.append(node('p','details',`${a.shares.toLocaleString('ja-JP')}株 · 平均取得 ${yen(a.cost)} · 現在 ${yen(a.price)}`));if(a.type==='fund')card.append(node('p','details',`取得総額 ${yen(a.invested)}`));if(['fund','stock'].includes(a.type)){const p=value(a)-cost(a);const line=node('div','asset-profit');line.append(node('span','','含み損益'),node('strong',p<0?'loss':'gain',`${signed(p)}${cost(a)?` (${p>0?'+':''}${(p/cost(a)*100).toFixed(1)}%)`:''}`));card.append(line);}$('#assets').append(card);}}
function fields(a={}){const type=$('#type').value;$('#fields').replaceChildren();const specs=type==='stock'?[['shares','株数','株',1],['cost','平均取得単価','円',0],['price','現在価格','円',0]]:type==='fund'?[['invested','取得総額','円',0],['amount','現在評価額','円',0]]:[['amount',type==='bond'?'保有額（額面）':'残高','円',0]];for(const [key,title,unit,min]of specs){const label=node('label','',title);const wrap=node('div','number-field');const input=node('input');input.name=key;input.type='number';input.inputMode=key==='shares'?'numeric':'decimal';input.min=min;input.max=1e12;input.step=key==='shares'?'1':'any';input.required=true;input.placeholder='0';if(a[key]!==undefined)input.value=a[key];wrap.append(input,node('span','',unit));label.append(wrap);$('#fields').append(label);}}
function openEditor(a){editing=a?.id??null;$('#form-title').textContent=a?'資産を編集':'資産を追加';$('#form-error').textContent='';$('#asset-form').reset();$('#type').value=a?.type??'cash';$('#name').value=a?.name??'';$('#institution').value=a?.institution??'';$('#account').value=a?.account??'';for(const key of ['institution','account']){$(`#${key}-options`).replaceChildren(...[...new Set(data.assets.map(x=>x[key]).filter(Boolean))].map(v=>{const option=node('option');option.value=v;return option;}));}fields(a);$('#editor').showModal();}
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();$('#type').onchange=()=>fields();$('#asset-form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target);const a={id:editing??crypto.randomUUID(),type:f.get('type'),name:f.get('name').trim(),institution:f.get('institution').trim(),account:f.get('account').trim()};for(const [k,v]of f)if(!['type','name','institution','account'].includes(k))a[k]=Number(v);validateAsset(a);const assets=editing?data.assets.map(x=>x.id===editing?a:x):[...data.assets,a];if(persist({version:1,assets,updated:new Date().toISOString()})){$('#editor').close();notice('資産を保存しました。');}}catch(err){$('#form-error').textContent=err.message;}};
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();$('#confirm-delete').onclick=()=>{if(persist({...data,assets:data.assets.filter(a=>a.id!==deleting),updated:new Date().toISOString()})){$('#delete-dialog').close();notice('資産を削除しました。');}};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=`portfolio-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('バックアップを書き出しました。「ファイル」などに保存してください。');};
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw new Error('ファイルが大きすぎます。');const next=parseBackup(await file.text());if(confirm(`${next.assets.length}件の資産を読み込み、現在のデータを置き換えます。よろしいですか？`))if(persist({...next,updated:new Date().toISOString()}))notice('バックアップを復元しました。');}catch(err){notice(`読み込めませんでした：${err.message}`);}e.target.value='';};
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
