import {normalizeCode,validCode,fetchQuote,applyQuotes} from './quotes.js';
import {TYPES,COLORS,value,cost,summary,institutionSummary,validateAsset,parseBackup} from './model.js';
const $=s=>document.querySelector(s), STORAGE='my-portfolio-v1';
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:2}).format(n);
const signed=n=>(n>0?'+':'')+yen(n);
let endpoint='';try{endpoint=localStorage.getItem('portfolio-quote-endpoint')??'';}catch{}
let refreshing=false,refreshQueued=false,lastAttempt=0,quoteErrors=new Map();
let data={version:1,assets:[],updated:null},editing=null,deleting=null;
function notice(message){$('#notice').textContent=message;}
try {const raw=localStorage.getItem(STORAGE);if(raw)data=parseBackup(raw);}catch {notice('保存データを読み込めませんでした。元のデータは上書きせず、バックアップからの復元をお試しください。');$('#add').disabled=true;}
function persist(next){try {localStorage.setItem(STORAGE,JSON.stringify(next));data=next;$('#add').disabled=false;render();return true;}catch {notice('保存できませんでした。ブラウザの空き容量・保存設定を確認してください。');return false;}}
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function render(){const s=summary(data.assets);const missing=data.assets.filter(a=>a.type==='stock'&&a.price===null).length;$('#valuation-warning').textContent=missing?`株価未取得の日本株が${missing}件あります。総資産・配分・損益・金融機関合計には含めていません。`:'';$('#total').textContent=yen(s.total);$('#profit').textContent=signed(s.profit);$('#profit').className=s.profit<0?'negative':'';$('#rate').textContent=s.rate===null?'—':`${s.rate>0?'+':''}${s.rate.toFixed(1)}%`;$('#updated').textContent=data.updated?`${new Date(data.updated).toLocaleDateString('ja-JP')} 更新`:'まだ登録がありません';$('#category-count').replaceChildren(document.createTextNode(String(Object.values(s.allocation).filter(v=>v>0).length)),node('span','', '種類'));$('#asset-count').textContent=`${data.assets.length}件の資産`;
 let start=0;const stops=[];$('#allocation-list').replaceChildren();for(const [t,label]of Object.entries(TYPES)){const pct=s.total?s.allocation[t]/s.total*100:0;stops.push(`${COLORS[t]} ${start}% ${start+pct}%`);start+=pct;const li=node('li');const left=node('div','legend-name');const dot=node('i');dot.style.background=COLORS[t];left.append(dot,node('span','',label));const right=node('div','legend-value');right.append(node('strong','',yen(s.allocation[t])),node('span','',`${pct.toFixed(1)}%`));li.append(left,right);$('#allocation-list').append(li);}$('#donut').style.background=s.total?`conic-gradient(${stops.join(',')})`:'#e8eeea';
 $('#institutions').replaceChildren();const groups=institutionSummary(data.assets);if(!groups.length)$('#institutions').append(node('p','details','資産を登録すると金融機関ごとの合計が表示されます。'));for(const group of groups){const section=node('div','institution-group');const heading=node('div','institution-heading');heading.append(node('strong','',group.name),node('strong','',yen(group.total)));section.append(heading);for(const account of group.accounts){const row=node('div','account-row');row.append(node('span','',account.name),node('span','',yen(account.total)));section.append(row);}$('#institutions').append(section);}
 $('#assets').replaceChildren();if(!data.assets.length){const empty=node('div','empty');empty.append(node('div','empty-icon','＋'),node('h3','','最初の資産を登録しましょう'),node('p','','現金からでも、保有している株からでも。'));$('#assets').append(empty);}
 for(const a of data.assets){const card=node('article','asset-card');const top=node('div','asset-top');const label=node('div');const badge=node('span','badge',TYPES[a.type]);badge.style.borderColor=COLORS[a.type];label.append(badge,node('h3','',a.name));const actions=node('div','asset-actions');const edit=node('button','','編集');edit.setAttribute('aria-label',`${a.name}を編集`);edit.onclick=()=>openEditor(a);const del=node('button','delete','削除');del.setAttribute('aria-label',`${a.name}を削除`);del.onclick=()=>{deleting=a.id;$('#delete-name').textContent=a.name;$('#delete-dialog').showModal();};actions.append(edit,del);top.append(label,actions);card.append(top,node('p','account-label',a.institution ? `${a.institution} ／ ${a.account}` : '口座未登録 · 編集から設定できます'),node('div','asset-value',a.type==='stock'&&a.price===null?'—':yen(value(a))));
 if(a.type==='stock'){card.append(node('p','details',`${a.code?`証券コード ${a.code} · `:''}${a.shares.toLocaleString('ja-JP')}株 · 平均取得 ${yen(a.cost)} · 現在 ${a.price===null?'未取得':yen(a.price)}`));card.append(node('p','details',a.quoteTime?`${a.quoteSource??'Yahoo Finance'} · 株価日時 ${new Date(a.quoteTime*1000).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}（日本時間・遅延の可能性あり）`:a.code?'自動取得待ち（保存済み価格は維持）':'証券コード未登録 · 編集から追加してください'));if(quoteErrors.has(a.code))card.append(node('p','quote-error',quoteErrors.get(a.code)));}if(a.type==='fund')card.append(node('p','details',`取得総額 ${yen(a.invested)}`));if(a.type==='stock'&&a.price===null){const pending=node('div','asset-profit');pending.append(node('span','','含み損益'),node('strong','','—（株価未取得）'));card.append(pending);}if(['fund','stock'].includes(a.type)&&a.price!==null){const p=value(a)-cost(a);const line=node('div','asset-profit');line.append(node('span','','含み損益'),node('strong',p<0?'loss':'gain',`${signed(p)}${cost(a)?` (${p>0?'+':''}${(p/cost(a)*100).toFixed(1)}%)`:''}`));card.append(line);}$('#assets').append(card);}}
function fields(a={}){const type=$('#type').value;$('#fields').replaceChildren();if(type==='stock'){const label=node('label','','証券コード（東証）');const input=node('input');input.name='code';input.maxLength=6;input.placeholder='例：7203、130A';input.value=a.code??'';input.required=true;input.autocapitalize='characters';label.append(input);$('#fields').append(label,node('p','details','現在株価は自動取得します。取得前は評価額・損益が未確定になります。'));}const specs=type==='stock'?[['shares','株数','株',1],['cost','平均取得単価','円',0]]:type==='fund'?[['invested','取得総額','円',0],['amount','現在評価額','円',0]]:[['amount',type==='bond'?'保有額（額面）':'残高','円',0]];for(const [key,title,unit,min]of specs){const label=node('label','',title);const wrap=node('div','number-field');const input=node('input');input.name=key;input.type='number';input.inputMode=key==='shares'?'numeric':'decimal';input.min=min;input.max=1e12;input.step=key==='shares'?'1':'any';input.required=true;input.placeholder='0';if(a[key]!==undefined)input.value=a[key];wrap.append(input,node('span','',unit));label.append(wrap);$('#fields').append(label);}}
function openEditor(a){editing=a?.id??null;$('#form-title').textContent=a?'資産を編集':'資産を追加';$('#form-error').textContent='';$('#asset-form').reset();$('#type').value=a?.type??'cash';$('#name').value=a?.name??'';$('#institution').value=a?.institution??'';$('#account').value=a?.account??'';for(const key of ['institution','account']){$(`#${key}-options`).replaceChildren(...[...new Set(data.assets.map(x=>x[key]).filter(Boolean))].map(v=>{const option=node('option');option.value=v;return option;}));}fields(a);$('#editor').showModal();}
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();$('#type').onchange=()=>fields();$('#asset-form').onsubmit=e=>{e.preventDefault();try{const f=new FormData(e.target);const a={id:editing??crypto.randomUUID(),type:f.get('type'),name:f.get('name').trim(),institution:f.get('institution').trim(),account:f.get('account').trim()};for(const [k,v]of f)if(!['type','name','institution','account','code'].includes(k))a[k]=Number(v);if(a.type==='stock'){a.code=normalizeCode(f.get('code'));const previous=data.assets.find(x=>x.id===editing);a.price=previous?.type==='stock'&&(!previous.code||previous.code===a.code)?previous.price:null;if(previous?.code===a.code&&previous.quoteTime){a.quoteTime=previous.quoteTime;a.quoteSource=previous.quoteSource;}}validateAsset(a);const assets=editing?data.assets.map(x=>x.id===editing?a:x):[...data.assets,a];if(persist({version:1,assets,updated:new Date().toISOString()})){$('#editor').close();notice('資産を保存しました。');refreshQuotes();}}catch(err){$('#form-error').textContent=err.message;}};
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();$('#confirm-delete').onclick=()=>{if(persist({...data,assets:data.assets.filter(a=>a.id!==deleting),updated:new Date().toISOString()})){$('#delete-dialog').close();notice('資産を削除しました。');}};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download=`portfolio-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notice('バックアップを書き出しました。「ファイル」などに保存してください。');};
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2e6)throw new Error('ファイルが大きすぎます。');const next=parseBackup(await file.text());if(confirm(`${next.assets.length}件の資産を読み込み、現在のデータを置き換えます。よろしいですか？`))if(persist({...next,updated:new Date().toISOString()})){notice('バックアップを復元しました。');refreshQuotes();}}catch(err){notice(`読み込めませんでした：${err.message}`);}e.target.value='';};
async function refreshQuotes(){
 if(refreshing){refreshQueued=true;return;}const codes=[...new Set(data.assets.filter(a=>a.type==='stock'&&validCode(a.code)).map(a=>a.code))];
 if(!codes.length){$('#quote-status').textContent='証券コードを登録すると株価を取得できます。';return;}
 if(!endpoint){$('#quote-status').textContent='株価取得サービスのURLを設定してください。以前の価格は維持しています。';return;}
 refreshing=true;lastAttempt=Date.now();$('#refresh-quotes').disabled=true;$('#quote-status').textContent='株価を取得しています…';
 const requestEndpoint=endpoint;const quotes=new Map();quoteErrors=new Map();
 for(const code of codes){try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{quotes.set(code,await fetchQuote(requestEndpoint,code,{signal:controller.signal}));}finally{clearTimeout(timer);}}catch(error){quoteErrors.set(code,error.name==='AbortError'?'取得がタイムアウトしました。以前の株価を維持しています。':error.message);}}
 let saved=true;if(endpoint===requestEndpoint&&quotes.size){try{const assets=applyQuotes(data.assets,quotes);for(const a of assets)validateAsset(a);saved=persist({...data,assets,updated:new Date().toISOString()});}catch{saved=false;}}
 refreshing=false;$('#refresh-quotes').disabled=false;render();$('#quote-status').textContent=!saved?'取得した株価を保存できませんでした。以前の価格を維持しています。':`取得 ${quotes.size}銘柄 ／ 失敗 ${quoteErrors.size}銘柄。失敗した銘柄の価格は変更していません。`;
 if(refreshQueued){refreshQueued=false;refreshQuotes();}
}
$('#quote-endpoint').value=endpoint;
$('#save-endpoint').onclick=()=>{try{const raw=$('#quote-endpoint').value.trim();if(raw){const url=new URL(raw);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw new Error('認証情報やクエリを含まないHTTPSのURLを入力してください。');}if(refreshing)throw new Error('株価取得が終わってから保存してください。');localStorage.setItem('portfolio-quote-endpoint',raw);endpoint=raw;$('#quote-status').textContent=raw?'接続先を保存しました。':'自動取得を停止しました。';if(raw)refreshQuotes();}catch(error){$('#quote-status').textContent=error.message;}};
$('#refresh-quotes').onclick=()=>refreshQuotes();
render();refreshQuotes();setInterval(()=>{if(document.visibilityState==='visible')refreshQuotes();},300000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastAttempt>=300000)refreshQuotes();});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
