import test from 'node:test';import assert from 'node:assert/strict';import {summary,validateAsset,parseBackup} from '../model.js';
const assets=[{id:'1',type:'cash',name:'預金',amount:100000},{id:'2',type:'bond',name:'国債',amount:200000},{id:'3',type:'fund',name:'オルカン',amount:330000,invested:300000},{id:'4',type:'stock',name:'日本株',shares:100,cost:1500,price:1200}];
test('4種類の総資産・損益・配分を計算する',()=>{assert.deepEqual(summary(assets),{total:750000,profit:0,rate:0,allocation:{cash:100000,bond:200000,fund:330000,stock:120000}});});
test('利益と損失、取得額ゼロを扱う',()=>{assert.equal(summary([assets[2]]).rate,10);assert.equal(summary([assets[3]]).rate,-20);assert.equal(summary([{...assets[2],invested:0}]).rate,null);assert.equal(summary([]).total,0);});
test('不正な数値と株数を拒否する',()=>{for(const price of [-1,NaN,Infinity,'1200'])assert.throws(()=>validateAsset({...assets[3],price}));assert.throws(()=>validateAsset({...assets[3],shares:1.2}));assert.throws(()=>validateAsset({...assets[3],shares:0}));assert.throws(()=>validateAsset({...assets[0],name:' '}));});
test('バックアップを検証して往復する',()=>{const backup={version:1,assets,updated:null};assert.deepEqual(parseBackup(JSON.stringify(backup)),backup);assert.throws(()=>parseBackup('{'));assert.throws(()=>parseBackup(JSON.stringify({...backup,version:2})));assert.throws(()=>parseBackup(JSON.stringify({...backup,assets:[assets[0],assets[0]]})));});

import {institutionSummary} from '../model.js';
test('旧データは変更せず口座未登録にまとめる',()=>{const original=JSON.stringify({version:1,assets,updated:null});const loaded=parseBackup(original);assert.equal(JSON.stringify(loaded),original);assert.deepEqual(institutionSummary(loaded.assets),[{name:'口座未登録',total:750000,accounts:[{name:'未登録',total:750000}]}]);});
test('金融機関と口座の内訳は総資産を二重計上しない',()=>{const entries=assets.map((a,i)=>({...a,institution:i===0?'SBI新生銀行':'SBI証券',account:i===0?'普通預金':i===2?'NISA':'特定口座'}));const groups=institutionSummary(entries);assert.equal(groups.reduce((n,g)=>n+g.total,0),summary(entries).total);assert.deepEqual(groups[1],{name:'SBI証券',total:650000,accounts:[{name:'特定口座',total:320000},{name:'NISA',total:330000}]});const moved=entries.map(a=>a.id==='3'?{...a,account:'特定口座'}:a);assert.equal(summary(moved).total,750000);assert.equal(institutionSummary(moved)[1].accounts.length,1);assert.deepEqual(parseBackup(JSON.stringify({version:1,assets:entries})).assets,entries);});
test('複数口座や不正な口座データを拒否する',()=>{assert.throws(()=>validateAsset({...assets[0],institution:['銀行1','銀行2'],account:'普通預金'}));assert.throws(()=>validateAsset({...assets[0],institution:'銀行',account:''}));assert.throws(()=>validateAsset({...assets[0],institution:'銀行',account:'a'.repeat(81)}));validateAsset({...assets[0],institution:'__proto__',account:'NISA'});});
